apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-v2-pv-workspace
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /vm/nfs/application/sample/sample-v2
    server: nfs.ocp4.local
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  volumeMode: Filesystem
