apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-v2-pvc-workspace
  namespace: sample
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc
  volumeMode: Filesystem
  volumeName: sample-v2-pv-workspace
