apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-v1-pvc-workspace
  namespace: sample
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc
  volumeMode: Filesystem
  volumeName: demo-v1-pv-workspace
