apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-v1-pv-workspace
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /vm/nfs/application/sample/demo-v1
    server: nfs.ocp4.local
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  volumeMode: Filesystem
